FROM ghcr.io/osgeo/gdal:ubuntu-small-3.6.3

ADD . /opt/grib-tiler
WORKDIR /opt/grib-tiler

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential git-core python3-dev
RUN curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3 get-pip.py
RUN python3 -m pip install -r requirements.txt --trusted-host dev.modext.ru --index-url http://__token__:glpat-MjaBuq7ExFVnCxefTUqu@dev.modext.ru:8929/api/v4/projects/329/packages/pypi/simple